### ISSUE TITLE
金字塔下采样时候的尺寸是不是有问题，不能整除的情况会出现bug吧？还有计算权重时候的矩阵是不是该初始化为全零？

### ISSUE THREAD

**Issue by liuhuaer** [jzsherlock4869/exposure-fusion-cpp#1]

**Comment by jzsherlock4869** [comment]
金字塔下采样尺寸已修改为round(s/2)；权重初始化已添加，感谢指正~（另增加了robust norm模块，自适应调整输出结果的亮度对比度）。
The size of each pyramid downscale is set to round(s/2), and weightmap initialization has been added. Thanks for pointing out~ (moreover, robust norm is applied to adjust lightness and contrast adaptively).
